#!/usr/bin/env bash
# setup nginx and configure listen on port 80
# displays "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start